
build_targets:
  - name: latest
    container:
      image: yourbase/yb_mono:5.18.1
    commands:
     - bash ./mono/build-mono.sh 
     - bash ./mono/test-mono.sh

ci:
  builds:
    - name: latest
      build_target: latest
